### ISSUE TITLE
Canon EOS 5D Mark 3 turns purple after conversion

### ISSUE THREAD

**Issue by levis9527** [ncruces/dcraw#2]
Hello, I want to ask, when I use the dcraw default parameter to convert cr2, the highlights of some camera models are purple, which is a common problem or the method I use is incorrect. 
The command is `dcraw -6 -T -w -O out.tiff 20230224134749262000473_ori_00183.CR2`

The link to the original image is `https://saas-cs.gdoss.xstore.ctyun.cn/20230316091635462000950/ori/20230316091635462000950_ori_00004.CR2`

My conversion diagram link is `https://saas-cs.gdoss.xstore.ctyun.cn/20230316091635462000950/ori/20230316091635462000950_ori_00004.jpg`

**Comment by ncruces** [comment]
Please see highlight recovery on the [man page for dcraw](https://linux.die.net/man/1/dcraw).
