### ISSUE TITLE
incorrect tags in 16bit tiff

### ISSUE THREAD

**Issue by michalfratczak** [ncruces/dcraw#3]
It seems several applications have problem reading 16 bit tiff files generated from dcraw.
One of them is Ricoh Stitcher desktop app (crash), another one is tifftools python package. 

I reported this to tifftools here: https://github.com/DigitalSlideArchive/tifftools/issues/83
The conclusion is that dcraw incorrectly writes tags. Can you please take a lookt at this ?

The minimal python code to reproduce is this:

`pip install tifftools
import tifftools
info = tifftools.read_tiff('photograph.tif')`

**Comment by ncruces** [comment]
Hi!
I'm not the author of dcraw, I just mirror the code here.
I'm OK with taking PRs for simple fixes like these, though.

**Comment by OscarChavarro** [comment]
Hello there!

What is the status of this project? I have been using this code for some time now, but in the original form (huge `dcraw.c` with all code inside), adding new contributions will be quite... un-confortable :P 

Is it possible to do some refactoring, splitting the code in several different .h / .c modules and provide a CMakeLists.txt to build with cmake? it this is possible, I will be happy to send PRs, and take a look also on adding support to 16 bits TIFF files.

**Comment by xiaosanxiao13** [comment]
我用这个应用于dng文件生成的tiff是黑色的，这正常吗，请问
