### ISSUE TITLE
Suggest keeping old release binaries

### ISSUE THREAD

**Issue by solarispika** [ncruces/dcraw#6]
Hello there,
I found that release v9.28.7 disappeared, which caused my project fail to get the binary for macOS.
Is it possible to keep old releases in the future?

**Comment by ncruces** [comment]
Sorry! Never thought these would get used in automated processes.

I'll get the previous macOS version back up, but could I also suggest subscribing the project for releases if you're using them that way?

Thanks!

**Comment by ncruces** [comment]
PS/FYI, if you want more control, this repository is designed to make it easy to fork and run its actions/workflows against specific tags to produce the desired binaries for macOS/Linux/Windows/WASM.

**Comment by solarispika** [comment]
Hello @ncruces

I will find some time to investigate how to migrate the actions/workflows to GitLab, where my project locates.
Thanks for your quick response and advices.

**Comment by ncruces** [comment]
Yeah, GitLab might be complicated.

Still, I promise to do better with releases in the future.
