### ISSUE TITLE
Request for demo code to use dcraw.wasm in a browser

### ISSUE THREAD

**Issue by ysmo** [ncruces/dcraw#7]
Hi @ncruces,

First of all, thank you for your work on dcraw and for creating the ncruces-wasm branch to support dcraw in a browser environment. This functionality is exactly what I need for my current project.

However, I’m having difficulty getting started with dcraw.wasm. I couldn’t find any example or demo code on how to properly load and use dcraw.wasm in a browser. It would be incredibly helpful if you could provide a basic example demonstrating how to use dcraw.wasm to process CR2 files and display the converted images in the browser.

Specifically, I’m looking for a simple HTML page with JavaScript that:

	1.	Allows the user to select a CR2 file.
	2.	Uses dcraw.wasm to convert the selected CR2 file to a JPEG.
	3.	Displays the resulting JPEG image on the page.

Here’s a brief outline of what I have in mind:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dcraw.wasm Demo</title>
</head>
<body>
    <h1>dcraw.wasm Demo</h1>
    <input type="file" id="fileInput" accept=".cr2">
    <img id="outputImage" alt="Converted Image">
    <script src="dcraw.js"></script>
</body>
</html>
```

```javascript
// dcraw.js
async function loadWasmModule() {
    const response = await fetch('dcraw.wasm');
    const bytes = await response.arrayBuffer();

    const importObj = {
        wasi_snapshot_preview1: {
            args_get: () => {},
            fd_write: () => {},
            fd_read: () => {},
            fd_close: () => {},
            proc_exit: () => {},
            // other necessary WASI imports
        }
    };

    const { instance } = await WebAssembly.instantiate(bytes, importObj);
    return instance;
}

async function processFile(file) {
    const instance = await loadWasmModule();
    const reader = new FileReader();

    reader.onload = function() {
        const arrayBuffer = reader.result;
        // Process the CR2 file with dcraw.wasm
        // Display the output image in the <img> tag
    };

    reader.readAsArrayBuffer(file);
}

document.getElementById('fileInput').addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (file) {
        processFile(file);
    }
});
```

I believe such a demo would be invaluable not only for me but also for others who are trying to use dcraw.wasm in their projects.

Thank you for your time and for considering this request.

Best regards,
ysmo

**Comment by ncruces** [comment]
`dcraw.wasm` isn't meant for browser use, but rather for WASI.

You probably want something like:
https://github.com/eschaefer/wasm-dcraw

**Comment by ysmo** [comment]
Thank you very much！
