### ISSUE TITLE
DNG 1.7.0.0

### ISSUE THREAD

**Issue by fdulau** [ncruces/dcraw#8]
It seems that the new DNG 1.7.0.0 using JPEG XL compression (0xCD42) is not yet supported.
This format is used by samsung s23 ultra latest expert Raw
How can I help with this issue?

**Comment by ncruces** [comment]
Hi! I'm not the author of dcraw, I just mirror the code here, and provide builds.
Contact the original author at his website: https://dechifro.org/dcraw/
